sow:
  class: Sow

syntax:
  class: Syntax

stats:
  class: Stats

notes:
  class: Notes

test:
  class: TestUnit

rdoc:
  class    : RDoc
  template : ./admin/config/rdoc-template
  inline   : true
  exclude  :
    - doc/rdoc
    - doc/ri

ri:
  class: RIDoc

gem:
  class: Gem

rubyforge:
  class   : Rubyforge
  groupid : 6829

