--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: []

full_name: Setup::ConfigTable::MetaConfigEnvironment#add_config
is_singleton: false
name: add_config
params: (name, default, desc)
visibility: public
