--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: []

full_name: Setup::ConfigTable::MetaConfigEnvironment#config_names
is_singleton: false
name: config_names
params: ()
visibility: public
