--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: []

full_name: Setup::ConfigTable::MetaConfigEnvironment#path_config?
is_singleton: false
name: path_config?
params: (name)
visibility: public
