--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Setup configuration. This comes from the <tt>session</tt> object.
full_name: Setup::Command#configuration
is_singleton: false
name: configuration
params: ()
visibility: public
