--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: []

full_name: Setup::Command#optparse_config
is_singleton: false
name: optparse_config
params: (parser, options)
visibility: public
