--- !ruby/object:RDoc::RI::ClassDescription 
attributes: []

class_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: new
- !ruby/object:RDoc::RI::MethodSummary 
  name: option
- !ruby/object:RDoc::RI::MethodSummary 
  name: options
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Stores platform information and general install settings.
- !ruby/struct:RDoc::Markup::Flow::RULE 
  width: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Stores platform information and general install settings.
constants: 
- !ruby/object:RDoc::RI::Constant 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Confgiuration file
  name: CONFIG_FILE
  value: "'SetupConfig'"
- !ruby/object:RDoc::RI::Constant 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Custom configuration file.
  name: META_CONFIG_FILE
  value: META_EXTENSION_DIR + '/configuration.rb'
- !ruby/object:RDoc::RI::Constant 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: Ruby System Configuration
  name: RBCONFIG
  value: "::Config::CONFIG"
full_name: Setup::Configuration
includes: []

instance_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: base_bindir
- !ruby/object:RDoc::RI::MethodSummary 
  name: base_datadir
- !ruby/object:RDoc::RI::MethodSummary 
  name: base_docdir
- !ruby/object:RDoc::RI::MethodSummary 
  name: base_libdir
- !ruby/object:RDoc::RI::MethodSummary 
  name: base_localstatedir
- !ruby/object:RDoc::RI::MethodSummary 
  name: base_mandir
- !ruby/object:RDoc::RI::MethodSummary 
  name: base_rubyarchdir
- !ruby/object:RDoc::RI::MethodSummary 
  name: base_rubylibdir
- !ruby/object:RDoc::RI::MethodSummary 
  name: base_sysconfdir
- !ruby/object:RDoc::RI::MethodSummary 
  name: bindir
- !ruby/object:RDoc::RI::MethodSummary 
  name: bindir=
- !ruby/object:RDoc::RI::MethodSummary 
  name: boolean
- !ruby/object:RDoc::RI::MethodSummary 
  name: compile?
- !ruby/object:RDoc::RI::MethodSummary 
  name: datadir
- !ruby/object:RDoc::RI::MethodSummary 
  name: datadir=
- !ruby/object:RDoc::RI::MethodSummary 
  name: docdir
- !ruby/object:RDoc::RI::MethodSummary 
  name: docdir=
- !ruby/object:RDoc::RI::MethodSummary 
  name: document?
- !ruby/object:RDoc::RI::MethodSummary 
  name: exist?
- !ruby/object:RDoc::RI::MethodSummary 
  name: extconfopt
- !ruby/object:RDoc::RI::MethodSummary 
  name: extconfopt=
- !ruby/object:RDoc::RI::MethodSummary 
  name: home
- !ruby/object:RDoc::RI::MethodSummary 
  name: initialize_configfile
- !ruby/object:RDoc::RI::MethodSummary 
  name: initialize_defaults
- !ruby/object:RDoc::RI::MethodSummary 
  name: initialize_environment
- !ruby/object:RDoc::RI::MethodSummary 
  name: initialize_metaconfig
- !ruby/object:RDoc::RI::MethodSummary 
  name: installdirs
- !ruby/object:RDoc::RI::MethodSummary 
  name: installdirs=
- !ruby/object:RDoc::RI::MethodSummary 
  name: libdir
- !ruby/object:RDoc::RI::MethodSummary 
  name: libdir=
- !ruby/object:RDoc::RI::MethodSummary 
  name: libruby
- !ruby/object:RDoc::RI::MethodSummary 
  name: libruby=
- !ruby/object:RDoc::RI::MethodSummary 
  name: librubyver
- !ruby/object:RDoc::RI::MethodSummary 
  name: librubyver=
- !ruby/object:RDoc::RI::MethodSummary 
  name: librubyverarch
- !ruby/object:RDoc::RI::MethodSummary 
  name: librubyverarch=
- !ruby/object:RDoc::RI::MethodSummary 
  name: localstatedir
- !ruby/object:RDoc::RI::MethodSummary 
  name: localstatedir=
- !ruby/object:RDoc::RI::MethodSummary 
  name: makeprog
- !ruby/object:RDoc::RI::MethodSummary 
  name: makeprog=
- !ruby/object:RDoc::RI::MethodSummary 
  name: mandir
- !ruby/object:RDoc::RI::MethodSummary 
  name: mandir=
- !ruby/object:RDoc::RI::MethodSummary 
  name: no_doc
- !ruby/object:RDoc::RI::MethodSummary 
  name: no_doc=
- !ruby/object:RDoc::RI::MethodSummary 
  name: no_ext
- !ruby/object:RDoc::RI::MethodSummary 
  name: no_ext=
- !ruby/object:RDoc::RI::MethodSummary 
  name: no_test
- !ruby/object:RDoc::RI::MethodSummary 
  name: no_test=
- !ruby/object:RDoc::RI::MethodSummary 
  name: options
- !ruby/object:RDoc::RI::MethodSummary 
  name: pathname
- !ruby/object:RDoc::RI::MethodSummary 
  name: prefix
- !ruby/object:RDoc::RI::MethodSummary 
  name: prefix=
- !ruby/object:RDoc::RI::MethodSummary 
  name: rbdir
- !ruby/object:RDoc::RI::MethodSummary 
  name: rubypath
- !ruby/object:RDoc::RI::MethodSummary 
  name: rubypath=
- !ruby/object:RDoc::RI::MethodSummary 
  name: rubyprog
- !ruby/object:RDoc::RI::MethodSummary 
  name: rubyprog=
- !ruby/object:RDoc::RI::MethodSummary 
  name: save_config
- !ruby/object:RDoc::RI::MethodSummary 
  name: shebang
- !ruby/object:RDoc::RI::MethodSummary 
  name: shebang=
- !ruby/object:RDoc::RI::MethodSummary 
  name: siteruby
- !ruby/object:RDoc::RI::MethodSummary 
  name: siteruby=
- !ruby/object:RDoc::RI::MethodSummary 
  name: siterubyver
- !ruby/object:RDoc::RI::MethodSummary 
  name: siterubyver=
- !ruby/object:RDoc::RI::MethodSummary 
  name: siterubyverarch
- !ruby/object:RDoc::RI::MethodSummary 
  name: siterubyverarch=
- !ruby/object:RDoc::RI::MethodSummary 
  name: sodir
- !ruby/object:RDoc::RI::MethodSummary 
  name: subprefix
- !ruby/object:RDoc::RI::MethodSummary 
  name: sysconfdir
- !ruby/object:RDoc::RI::MethodSummary 
  name: sysconfdir=
- !ruby/object:RDoc::RI::MethodSummary 
  name: test?
- !ruby/object:RDoc::RI::MethodSummary 
  name: to_h
- !ruby/object:RDoc::RI::MethodSummary 
  name: to_s
- !ruby/object:RDoc::RI::MethodSummary 
  name: to_yaml
- !ruby/object:RDoc::RI::MethodSummary 
  name: type
- !ruby/object:RDoc::RI::MethodSummary 
  name: type=
name: Configuration
superclass: Object
