--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: []

full_name: Setup::Configuration#initialize_metaconfig
is_singleton: false
name: initialize_metaconfig
params: ()
visibility: public
