--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Load configuration.
full_name: Setup::Configuration#initialize_configfile
is_singleton: false
name: initialize_configfile
params: ()
visibility: public
