--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Save configuration.
full_name: Setup::Configuration#save_config
is_singleton: false
name: save_config
params: ()
visibility: public
