sow:
  service: SowGen

syntax:
  service: Syntax

stats:
  service: BasicStats

notes:
  service: Notes

test:
  service: TestUnit

rdoc:
  service  : RDoc
  template : .config/rdoc-template
  inline   : true

ri:
  service: RIDoc

gem:
  service : Gem
  include : [ bin, doc, lib, meta, task, test, '[A-Z]*' ]
  exclude : [ doc/rdoc, doc/ri ]

rubyforge:
  service : Rubyforge
  groupid : 6829

