--- !ruby/object:RDoc::RI::ClassDescription 
attributes: []

class_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: attr_accessor
- !ruby/object:RDoc::RI::MethodSummary 
  name: attr_boolean
- !ruby/object:RDoc::RI::MethodSummary 
  name: attr_pathlist
- !ruby/object:RDoc::RI::MethodSummary 
  name: attr_pathname
- !ruby/object:RDoc::RI::MethodSummary 
  name: new
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Config stores platform information.
- !ruby/struct:RDoc::Markup::Flow::RULE 
  width: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Config stores platform information.
constants: 
- !ruby/object:RDoc::RI::Constant 
  comment: 
  name: CONFIGFILE
  value: "'.cache/setup/config'"
- !ruby/object:RDoc::RI::Constant 
  comment: 
  name: DESCRIPTIONS
  value: "[       [:prefix          , :path, 'path prefix of target environment'],       [:bindir          , :path, 'directory for commands'],       [:libdir          , :path, 'directory for libraries'],       [:datadir         , :path, 'directory for shared data'],       [:mandir          , :path, 'directory for man pages'],       [:docdir          , :path, 'Directory for documentation'],       [:sysconfdir      , :path, 'directory for system configuration files'],       [:localstatedir   , :path, 'directory for local state data'],       [:libruby         , :path, 'directory for ruby libraries'],       [:librubyver      , :path, 'directory for standard ruby libraries'],       [:librubyverarch  , :path, 'directory for standard ruby extensions'],       [:siteruby        , :path, 'directory for version-independent aux ruby libraries'],       [:siterubyver     , :path, 'directory for aux ruby libraries'],       [:siterubyverarch , :path, 'directory for aux ruby binaries'],       [:rbdir           , :path, 'directory for ruby scripts'],       [:sodir           , :path, 'directory for ruby extentions'],       [:rubypath        , :prog, 'path to set to #! line'],       [:rubyprog        , :prog, 'ruby program used for installation'],       [:makeprog        , :prog, 'make program to compile ruby extentions'],       [:extconfopt      , :name, 'options to pass-thru to extconf.rb'],       [:withoutext      , :bool, 'do not compile/install ruby extentions'],       [:withoutdoc      , :bool, 'do not generate documentation'],       [:shebang         , :pick, 'shebang line (#!) editing mode (all,ruby,never)'],       [:doctemplate     , :pick, 'document template to use (html|xml)'],       [:testrunner      , :pick, 'Runner to use for testing (auto|console|tk|gtk|gtk2)'],       [:installdirs     , :pick, 'install location mode (std,site,home :: libruby,site_ruby,$HOME)']     ]"
- !ruby/object:RDoc::RI::Constant 
  comment: 
  - !ruby/struct:RDoc::Markup::Flow::P 
    body: List of configurable options.
  name: OPTIONS
  value: DESCRIPTIONS.collect{ |(k,t,v)| k.to_s }
- !ruby/object:RDoc::RI::Constant 
  comment: 
  name: RBCONFIG
  value: "::Config::CONFIG"
full_name: Setup::ConfigTable
includes: []

instance_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: "[]"
- !ruby/object:RDoc::RI::MethodSummary 
  name: "[]="
- !ruby/object:RDoc::RI::MethodSummary 
  name: compiles?
- !ruby/object:RDoc::RI::MethodSummary 
  name: descriptions
- !ruby/object:RDoc::RI::MethodSummary 
  name: env_config
- !ruby/object:RDoc::RI::MethodSummary 
  name: extconfs
- !ruby/object:RDoc::RI::MethodSummary 
  name: extensions
- !ruby/object:RDoc::RI::MethodSummary 
  name: initialize_attributes
- !ruby/object:RDoc::RI::MethodSummary 
  name: initialize_defaults
- !ruby/object:RDoc::RI::MethodSummary 
  name: installdirs=
- !ruby/object:RDoc::RI::MethodSummary 
  name: load_config
- !ruby/object:RDoc::RI::MethodSummary 
  name: load_meta_config
- !ruby/object:RDoc::RI::MethodSummary 
  name: save_config
- !ruby/object:RDoc::RI::MethodSummary 
  name: shebang=
- !ruby/object:RDoc::RI::MethodSummary 
  name: show
name: ConfigTable
superclass: Object
