--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Setup::Installer#config_dir_ext
is_singleton: false
name: config_dir_ext
params: (rel)
visibility: public
