--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "obsolete: use metaconfig to change configuration TODO: what to do with?"
full_name: Setup::Installer#set_config
is_singleton: false
name: set_config
params: (key, val)
visibility: public
